name = "LoopOSAgentgodCommunication"
uuid = "7ce46cf5-3950-432b-9fe4-35478028831f"
version = "6.0.0"
authors = ["1m1 <imi@1m1.io>"]

[deps]
ZMQ = "c2297ded-f4af-51ae-bb23-16f91089e4e1"

[compat]
ZMQ = ">=1.5.1"
